### PR TITLE
UI Tests for TagDialogFragment

### LINKED ISSUE #1364: UI tests for TagDialogFragment (medium/integration tests)
Parent: #1361

TODO

Create class `TagDialogFragmentTest` and put it inside `androidTest`. Write the following tests for `TagDialogFragment`:

#### Test 1 - Edit a tag with a valid name

1. Create tag with name `tag1` and save it
2. Create note with content = "Hello World" with tags = [`tag1`]
3. Open `TagDialogFragment` and pass `Tag` object for `tag1`
4. Type `tag5` in the edit text for name of the tag
5. Click in `Save`
6. The number of tags should be 1 and the tag name should be updated to `tag5`
7. Tag `tag1` should not exists
8. Tag `tag5` should exists
9. The tags for note with content "Hello World" should be [`tag5`]

#### Test 2 - Try to edit a tag with a name too long

1. Create tag with name `tag1` and save it
2. Create note with content = "Hello World" with tags = [`tag1`]
3. Open `TagDialogFragment` and pass `Tag` object for `tag1`
4. Type a tag with more than 256 characters
5. The button `Save` must not be enabled
6. The error message "Tag length too long" is shown
7. Click on `Cancel` button
8. The tags for note with content "Hello World" should be [`tag1`]

#### Test 3 - Try to edit a tag with a space in the name

1. Create tag with name `tag10` and save it
2. Create note with content = "Hello World" with tags = [`tag10`]
3. Open `TagDialogFragment` and pass `Tag` object for `tag10`
4. Type a tag "tag 3"
5. The button `Save` must not be enabled
6. The error message "Tags cannot contain spaces" is shown
7. Click on `Cancel` button
8. Tags bucket should contain the same number of tags
9. The tags for note with content "Hello World" should be [`tag10`]

#### Test 4 - Try to edit a tag with an empty name

1. Create tag with name `tag10` and save it
2. Create note with content = "Hello World" with tags = [`tag10`]
3. Open `TagDialogFragment` and pass `Tag` object for `tag10`
4. Clean field
5. The button `Save` must not be enabled
6. The error message "Tags cannot be empty" is shown
7. Click on `Cancel` button
8. Tags bucket should contain the same number of tags
9. The tags for note with content "Hello World" should be [`tag10`]

#### Test 5 - Edit tag in multiple notes
1. Create tag with name `tag1` and save it
2. Create tag with name `tag2` and save it
3. Create tag with name `tag3` and save it
4. Create note with content = "Hello1" with tags = [`tag1`, `tag2`]
5. Create note with content = "Hello2" with tags = [`tag2`, `tag3`]
6. Create note with content = "Hello3" with tags = [`tag1`, `tag3`]
7. Open `TagDialogFragment` and pass `Tag` object for `tag2`
8. Type a tag "tag10"
9. Click in button `Save`
10. Tags bucket should contain the same number of tags (3)
11. The tags for note with content "Hello1" should be [`tag1`, `tag10`]
12. The tags for note with content "Hello2" should be [`tag10`, `tag3`]
13. The tags for note with content "Hello3" should be [`tag1`, `tag3`]

#### Test 6 - Try to merge a tag but go back and cancel
1. Create tag with name `tag1` and save it
2. Create tag with name `tag2` and save it
3. Create tag with name `tag3` and save it
4. Create note with content = "Hello1" with tags = [`tag1`, `tag2`]
5. Create note with content = "Hello2" with tags = [`tag2`, `tag3`]
6. Create note with content = "Hello3" with tags = [`tag1`, `tag3`]
7. Open `TagDialogFragment` and pass `Tag` object for `tag2`
8. Type a tag "tag3"
9. Click in button `Save`
10. Popup showing whether the user wants to merge the tag2 into tag3.
11. Click in button `Back`
10. Tags bucket should contain the same number of tags (3)
11. The tags for note with content "Hello1" should be [`tag1`, `tag2`]
12. The tags for note with content "Hello2" should be [`tag2`, `tag3`]
13. The tags for note with content "Hello3" should be [`tag1`, `tag3`]

#### Test 7 - Try to merge a tag but go back and cancel
1. Create tag with name `tag1` and save it
2. Create tag with name `tag2` and save it
3. Create tag with name `tag3` and save it
4. Create note with content = "Hello1" with tags = [`tag1`, `tag2`]
5. Create note with content = "Hello2" with tags = [`tag2`, `tag3`]
6. Create note with content = "Hello3" with tags = [`tag1`, `tag3`]
7. Open `TagDialogFragment` and pass `Tag` object for `tag2`
8. Type a tag "tag1"
9. Click in button `Save`
10. Popup showing whether the user wants to merge the tag2 into tag3.
11. Click in button `Merge`
10. Tags bucket should contain 2 tags [`tag1`, `tag3`]
11. The tags for note with content "Hello1" should be [`tag1`]
12. The tags for note with content "Hello2" should be [``tag3`, `tag1`]
13. The tags for note with content "Hello3" should be [`tag1`, `tag3`]

#### Test 8 - Make fail tag creation
1. Create tag with name `tag1` and save it
2. Create note with content = "Hello World" with tags = [`tag1`]
3. Open `TagDialogFragment` and pass `Tag` object for `tag1`
4. Type `tag5` in the edit text for name of the tag
5. Click in button `Save`
6. A message showing that there was en error should pop.
7. Click in button `OK`
7. The number of tags should be 1 and the tag name should be updated to `tag1`
8. Tag `tag1` should exists
9. Tag `tag5` should not exists
10. The tags for note with content "Hello World" should be [`tag1`]

### PR DESCRIPTION
**Pull request by dandominguez04**
Fixes #1364

### Fix
This PR adds UI tests for the activity `TagDialogFragment`. The tests are described in #1364. 

### Test
This PR adds UI tests and espresso utilities functions to tests scenarios of editing tags. 

1. Run `TagDialogFragmentTest` inside `androidTest`. It requires to run an on emulator or physical device. 

### Review
This PR will be reviewed by @ParaskP7. 

### Release
These changes do not require release notes.

### CODE REVIEW

File: Simplenote/src/androidTest/java/com/automattic/simplenote/utils/TestBucket.kt [hunk 1]
```diff
@@ -39,7 +54,102 @@ abstract class TestBucket<T : Syncable>(name: String) : Bucket<T>(null, name, nu
...
+    override fun getSimperiumKey(): String {
+        return objects[position].simperiumKey
+    }
+
+    override fun getObject(): T {
+        return objects[position]
+    }
+}
+
+class TestQuery<T : BucketObject>(private val objects:  MutableList<T>) : Query<T>() {
```
Comment (ParaskP7) [inline Simplenote/src/androidTest/java/com/automattic/simplenote/utils/TestBucket.kt:140]: Praise (❤️): This is nicely node, kudos!

File: Simplenote/src/androidTest/java/com/automattic/simplenote/integration/TagDialogFragmentTest.kt [hunk 2]
```diff
@@ -0,0 +1,326 @@
...
+import com.automattic.simplenote.utils.hasTextInputLayoutErrorText
+import org.hamcrest.CoreMatchers.allOf
+import org.hamcrest.CoreMatchers.not
+import org.junit.Assert.*
+import org.junit.Test
+import org.junit.runner.RunWith
+
+@RunWith(AndroidJUnit4ClassRunner::class)
+@MediumTest
+class TagDialogFragmentTest : BaseUITest() {
```
Comment (ParaskP7) [inline Simplenote/src/androidTest/java/com/automattic/simplenote/integration/TagDialogFragmentTest.kt:25]: 1) Praise (❤️): Such a nice work well done here, kudos!
2) Suggestion (💡): I wonder since you are checking for the dialog button names to be displayed and asserting their names, maybe we should do the same for the dialog titles as well, like `Tag Conflict` for the `editMergeTagInMultipleNotes` test. PS: The same applies to all tests.
3) Suggestion (💡): I am seeing the formatting of `onView(...)`, `.check(...)`, `.perform(...)`, etc, being done based on the space available in a specific line. I wonder whether formatting these lines to always break on the higher level `dot` might make them more readable. Wdyt? For example:
```
        onView(allOf(withText("tag1"), isDescendantOfA(withId(R.id.input_tag_name))))
            .check(matches(isDisplayed()))
        onView(allOf(withText("tag1"), isDescendantOfA(withId(R.id.input_tag_name))))
            .perform(ViewActions.replaceText("tag5"))

        onView(allOf(withText("tag5"), isDescendantOfA(withId(R.id.input_tag_name))))
            .check(matches(isDisplayed()))

        onView(withText(saveText)).inRoot(isDialog())
            .check(matches(isDisplayed()))
            .perform(click())
```

File: Simplenote/src/androidTest/java/com/automattic/simplenote/integration/TagDialogFragmentTest.kt [hunk 3]
```diff
@@ -0,0 +1,326 @@
...
+        val note = createNote("Hello World", listOf("tag10"))
+
+        assertEquals(tagsBucket.count(), 1)
+        assertEquals(notesBucket.count(), 1)
+
+        launchFragment("tag10")
+
+        onView(allOf(withText("tag10"), isDescendantOfA(withId(R.id.input_tag_name)))).check(matches(isDisplayed()))
+
+        onView(allOf(withText("tag10"), isDescendantOfA(withId(R.id.input_tag_name))))
```
Comment (ParaskP7) [inline Simplenote/src/androidTest/java/com/automattic/simplenote/integration/TagDialogFragmentTest.kt:121]: Suggestion (💡): Just like you did with the `val longName = getRandomString(258)` test above, what if we made this explicit as well, by extracting a variable: `val tagWithSpace = "tag 3"`

PS: Same applies for the potential `val emptyTag = ""` variable on the test below and any other such variable that can help with making the testing part explicit.

File: Simplenote/src/androidTest/java/com/automattic/simplenote/integration/TagDialogFragmentTest.kt [hunk 4]
```diff
@@ -0,0 +1,326 @@
...
+
+    @Test
+    fun editTagInMultipleNotes() {
+        createTag("tag1")
+        createTag("tag2")
+        createTag("tag3")
+        // To edit tags, tags should belong a note
+        val note1 = createNote("Hello1", listOf("tag1", "tag2"))
+        val note2 = createNote("Hello1", listOf("tag2", "tag3"))
+        val note3 = createNote("Hello1", listOf("tag1", "tag3"))
```
Comment (ParaskP7) [inline Simplenote/src/androidTest/java/com/automattic/simplenote/integration/TagDialogFragmentTest.kt]: Minor (🔍): Reader the test cases within [1364](https://github.com/Automattic/simplenote-android/issues/1364) issue I am seeing that the note names are `Hello1`, `Hello2` and `Hello3`. I know it doesn't matter much, but maybe it is good to have different notes and align those with the test cases issue. Wdyt?

PS: Same applies everywhere else.

File: Simplenote/src/androidTest/java/com/automattic/simplenote/integration/TagDialogFragmentTest.kt [hunk 5]
```diff
@@ -0,0 +1,326 @@
...
+        assertNotNull(tag1)
+        assertNotNull(tag3)
+
+        assertEquals(note1.tags, listOf("tag1", "tag2"))
+        assertEquals(note2.tags, listOf("tag2", "tag3"))
+        assertEquals(note3.tags, listOf("tag1", "tag3"))
+    }
+
+    @Test
+    fun editMergeTagInMultipleNotes() {
```
Comment (ParaskP7) [inline Simplenote/src/androidTest/java/com/automattic/simplenote/integration/TagDialogFragmentTest.kt:291]: Question (❓): This test is missing from the test cases within [1364](https://github.com/Automattic/simplenote-android/issues/1364) issue. Isn't it?

File: Simplenote/src/androidTest/java/com/automattic/simplenote/integration/TagDialogFragmentTest.kt [hunk 6]
```diff
@@ -0,0 +1,326 @@
...
+        onView(allOf(withText("tag1"), isDescendantOfA(withId(R.id.input_tag_name)))).check(matches(isDisplayed()))
+        onView(allOf(withText("tag1"), isDescendantOfA(withId(R.id.input_tag_name))))
+                .perform(ViewActions.replaceText("tag5"))
+        onView(allOf(withText("tag5"), isDescendantOfA(withId(R.id.input_tag_name)))).check(matches(isDisplayed()))
+
+        tagsBucket.newObjectShouldFail = true
+
+        val saveText = getResourceString(R.string.save)
+        onView(withText(saveText)).inRoot(isDialog()).check(matches(isDisplayed())).perform(click())
+
```
Comment (ParaskP7) [inline Simplenote/src/androidTest/java/com/automattic/simplenote/integration/TagDialogFragmentTest.kt:375]: Question (❓): In other tests within this test suite you are check whether the actual displayed error message matches the expected one. Can we do that here as well? I am seeing it is a bit complicated to assert that indeed since the error message is an HTML constructed one.

File: Simplenote/src/androidTest/java/com/automattic/simplenote/integration/TagDialogFragmentTest.kt [hunk 7]
```diff
@@ -0,0 +1,326 @@
...
+        val tag1 = getTag("tag1")
+        val tag5 = getTag("tag5")
+
+        assertNotNull(tag1)
+        assertNull(tag5)
+        assertEquals(tagsBucket.count(), 1)
+        assertEquals(note.tags, listOf("tag1"))
+    }
+
+    private fun launchFragment(tagName: String): FragmentScenario<TagDialogFragment> {
```
Comment (ParaskP7) [inline Simplenote/src/androidTest/java/com/automattic/simplenote/integration/TagDialogFragmentTest.kt]: Question (❓): The return value is not used anywhere, is it? Why would you want to return it anyway, is this something that will be needed later on in subsequent tests?

**Review by ParaskP7 — APPROVED** [review]
👋 @dandominguez04 !

I have reviewed and tested this PR as per the instructions, everything works as expected, amazing job, it gives me so much joy so be seeing this level of testing happening in Simplenote! 🌟 ❤️ 🌟 

I have left only minor (🔍) comments, some suggestions (💡) for you to consider and a few questions (❓). I am going to approve this PR anyway, since none is blocking. I am **NOT** going to merge this PR yet to give you some time to apply any of my suggestions.

File: Simplenote/src/androidTest/java/com/automattic/simplenote/utils/TestBucket.kt (hunk 1 above)
Comment (dandominguez04) [reply Simplenote/src/androidTest/java/com/automattic/simplenote/utils/TestBucket.kt:140]: Thanks!

File: Simplenote/src/androidTest/java/com/automattic/simplenote/integration/TagDialogFragmentTest.kt (hunk 5 above)
Comment (dandominguez04) [reply Simplenote/src/androidTest/java/com/automattic/simplenote/integration/TagDialogFragmentTest.kt:291]: Yes, that should be test 7. I have added the test to the issue.

File: Simplenote/src/androidTest/java/com/automattic/simplenote/integration/TagDialogFragmentTest.kt (hunk 6 above)
Comment (dandominguez04) [reply Simplenote/src/androidTest/java/com/automattic/simplenote/integration/TagDialogFragmentTest.kt:375]: Yes, let me check if  I can construct it.

File: Simplenote/src/androidTest/java/com/automattic/simplenote/integration/TagDialogFragmentTest.kt (hunk 7 above)
Comment (dandominguez04) [reply Simplenote/src/androidTest/java/com/automattic/simplenote/integration/TagDialogFragmentTest.kt]: Not in this particular test. I will remove it.

Comment (dandominguez04) [reply Simplenote/src/androidTest/java/com/automattic/simplenote/integration/TagDialogFragmentTest.kt]: Fixed in 801a30df4dd779591070e5eecdf28361191cb66c.

File: Simplenote/src/androidTest/java/com/automattic/simplenote/integration/TagDialogFragmentTest.kt (hunk 4 above)
Comment (dandominguez04) [reply Simplenote/src/androidTest/java/com/automattic/simplenote/integration/TagDialogFragmentTest.kt]: Fixed in 3bfd5bda11dc003ae4f9588e849af888c801f979.

File: Simplenote/src/androidTest/java/com/automattic/simplenote/integration/TagDialogFragmentTest.kt (hunk 3 above)
Comment (dandominguez04) [reply Simplenote/src/androidTest/java/com/automattic/simplenote/integration/TagDialogFragmentTest.kt:121]: Fixed in 0627e2a5a35b912fa67d8ecb20127df887f6c6ee. 

PS: I change a field visibility in BaseUITest and accidentally went into this commit.

File: Simplenote/src/androidTest/java/com/automattic/simplenote/integration/TagDialogFragmentTest.kt (hunk 2 above)
Comment (dandominguez04) [reply Simplenote/src/androidTest/java/com/automattic/simplenote/integration/TagDialogFragmentTest.kt:25]: > I wonder since you are checking for the dialog button names to be displayed and asserting their names, maybe we should do the same for the dialog titles as well, like Tag Conflict for the editMergeTagInMultipleNotes test. PS: The same applies to all tests.

Fixed in 17d3749d9a22c48cec193209444f7ba6f4ed1a2e.

Comment (dandominguez04) [reply Simplenote/src/androidTest/java/com/automattic/simplenote/integration/TagDialogFragmentTest.kt:25]: >  I am seeing the formatting of onView(...), .check(...), .perform(...), etc, being done based on the space available in a specific line. I wonder whether formatting these lines to always break on the higher level dot might make them more readable. Wdyt? 


Sounds good. Fixed in a411ab8c18c1d541f97812b4bcc03aa4fed54e17.

File: Simplenote/src/androidTest/java/com/automattic/simplenote/integration/TagDialogFragmentTest.kt (hunk 6 above)
Comment (dandominguez04) [reply Simplenote/src/androidTest/java/com/automattic/simplenote/integration/TagDialogFragmentTest.kt:375]: I could not find a way to check HTML. I tried with the same message in HTML and it did not work. There is not much information in the Internet either.

File: Simplenote/src/androidTest/java/com/automattic/simplenote/integration/TagDialogFragmentTest.kt (hunk 3 above)
Comment (ParaskP7) [reply Simplenote/src/androidTest/java/com/automattic/simplenote/integration/TagDialogFragmentTest.kt:121]: > PS: I change a field visibility in BaseUITest and accidentally went into this commit.

All good... 😅

File: Simplenote/src/androidTest/java/com/automattic/simplenote/integration/TagDialogFragmentTest.kt (hunk 6 above)
Comment (ParaskP7) [reply Simplenote/src/androidTest/java/com/automattic/simplenote/integration/TagDialogFragmentTest.kt:375]: I agree, it might get tricky indeed. 👌 

What would you say for us to create an issue on it so that to make sure everyone is aware of us knowingly doing so and then this way we can look again in isolation and if time allows later on?

**Review by ParaskP7 — APPROVED** [review]
LGTM! 🥇 

Thanks for making the effort to resolve all my comments. 🙏

File: Simplenote/src/androidTest/java/com/automattic/simplenote/integration/TagDialogFragmentTest.kt (hunk 6 above)
Comment (dandominguez04) [reply Simplenote/src/androidTest/java/com/automattic/simplenote/integration/TagDialogFragmentTest.kt:375]: Let add the issue and add it in the extra section.

Comment (dandominguez04) [reply Simplenote/src/androidTest/java/com/automattic/simplenote/integration/TagDialogFragmentTest.kt:375]: Issue: https://github.com/Automattic/simplenote-android/issues/1388
