### PR TITLE
Make Sure Activity is Still Active After loadNoteTask Finishes

### LINKED ISSUE #489: NPE in Markdown View
Probably also needs an `isAdded()` here after the task finishes... similar to #488 

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.invalidateOptionsMenu()' on a null object reference
       at com.automattic.simplenote.NoteMarkdownFragment$loadNoteTask.onPostExecute(Unknown Source)
       at com.automattic.simplenote.NoteMarkdownFragment$loadNoteTask.onPostExecute(Unknown Source)
       at android.os.AsyncTask.finish(AsyncTask.java:660)
       at android.os.AsyncTask.-wrap1(AsyncTask.java)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:677)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

### PR DESCRIPTION
**Pull request by robertoissc**
Fixes #489 by making sure the activity is still active and preventing a NPE.

### CODE REVIEW

File: Simplenote/src/main/java/com/automattic/simplenote/NoteMarkdownFragment.java [hunk 1]
```diff
@@ -162,7 +162,9 @@ protected void onPostExecute(Void nada) {
             mIsLoadingNote = false;
 
             if (mNote != null) {
-                getActivity().invalidateOptionsMenu();
+                if(getActivity() != null) {
```
Comment (roundhill) [inline Simplenote/src/main/java/com/automattic/simplenote/NoteMarkdownFragment.java]:
```suggestion
                if (getActivity() != null) {
```
Just need a space there ;) Looks good otherwise.

Comment (robertoissc) [reply Simplenote/src/main/java/com/automattic/simplenote/NoteMarkdownFragment.java]: Sorry about that!
