### PR TITLE
Integrate `Automattic-Tracks-Android 2.1.0`

### LINKED ISSUE #1386: Integrate `2.0.0` version of `Automattic-Tracks-Android`
https://github.com/Automattic/Automattic-Tracks-Android/releases/tag/2.0.0

New `Automattic-Tracks-Android` contains changes to how we integrate with Sentry SDK. This release contains a breaking change as `CrashLogging` class is no longer a static one. We should inject it into DI graph

### PR DESCRIPTION
**Pull request by wzieba**
Closes: #1386 

### Fix

This PR introduces integration with major Tracks update (from v1 to v2). The update contains numerous improvements to Track's crash logging API as well as Sentry SDK bump (from currently used 1.7.x to 5.0.x). It also fixes issue with not uploading mapping files to Sentry console for release builds.

Tracks `2.x` is already used in WordPress (https://github.com/wordpress-mobile/WordPress-Android/pull/14833) and WooCommerce (https://github.com/woocommerce/woocommerce-android/pull/3891) projects for some time.

#### Sending events to Sentry
1. Apply Git PATCH (available on the bottom of this description)
2. Open the app, login if necessary
3. Go to menu
4. Click on `Edit` on `Tags` section
5. Open Sentry.io dashboard
6. **Assert there's `Ignore me, it's just a test` issue. Make sure all needed data is attached to it.**
7. Delete the issue

#### Sending mapping files to Sentry
1. Go to repository directory
2. Build a release: `./gradlew assembleRelease`
3. **Assert the mappings are uploaded**. Make sure you see
```
> compressing mappings
> uploading mappings
> Uploaded a total of 1 new mapping files
Newly uploaded debug symbols:
```
in the ouput.

### Review

I can't find any additional instructions needed.

### Release

These changes do not require release notes.

---

```
Index: Simplenote/src/main/java/com/automattic/simplenote/utils/crashlogging/SimplenoteCrashLoggingDataProvider.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/Simplenote/src/main/java/com/automattic/simplenote/utils/crashlogging/SimplenoteCrashLoggingDataProvider.kt b/Simplenote/src/main/java/com/automattic/simplenote/utils/crashlogging/SimplenoteCrashLoggingDataProvider.kt
--- a/Simplenote/src/main/java/com/automattic/simplenote/utils/crashlogging/SimplenoteCrashLoggingDataProvider.kt	(revision 8b9b9a800a4ec7f4b2735d1594191feb8a850224)
+++ b/Simplenote/src/main/java/com/automattic/simplenote/utils/crashlogging/SimplenoteCrashLoggingDataProvider.kt	(date 1631529483873)
@@ -33,7 +33,7 @@
     }
 
     override fun crashLoggingEnabled(): Boolean {
-        return !Simplenote.analyticsIsEnabled()
+        return true
     }
 
     override fun extraKnownKeys(): List<ExtraKnownKey> {
Index: Simplenote/src/main/java/com/automattic/simplenote/TagsActivity.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/Simplenote/src/main/java/com/automattic/simplenote/TagsActivity.kt b/Simplenote/src/main/java/com/automattic/simplenote/TagsActivity.kt
--- a/Simplenote/src/main/java/com/automattic/simplenote/TagsActivity.kt	(revision 8b9b9a800a4ec7f4b2735d1594191feb8a850224)
+++ b/Simplenote/src/main/java/com/automattic/simplenote/TagsActivity.kt	(date 1631524813896)
@@ -14,6 +14,7 @@
 import androidx.appcompat.widget.SearchView
 import androidx.appcompat.widget.Toolbar
 import androidx.recyclerview.widget.LinearLayoutManager
+import com.automattic.android.tracks.crashlogging.CrashLogging
 import com.automattic.simplenote.databinding.ActivityTagsBinding
 import com.automattic.simplenote.utils.*
 import com.automattic.simplenote.viewmodels.TagsEvent
@@ -21,11 +22,15 @@
 import com.automattic.simplenote.viewmodels.TagsViewModel
 import com.automattic.simplenote.widgets.MorphSetup
 import dagger.hilt.android.AndroidEntryPoint
+import javax.inject.Inject
 
 @AndroidEntryPoint
 class TagsActivity : ThemedAppCompatActivity() {
     private val viewModel: TagsViewModel by viewModels()
 
+    @Inject
+    lateinit var crashLogging: CrashLogging
+
     public override fun onCreate(savedInstanceState: Bundle?) {
         super.onCreate(savedInstanceState)
 
@@ -36,6 +41,10 @@
         binding.setObservers()
 
         viewModel.start()
+
+        crashLogging.sendReport(
+            message = "Ignore me, it's just a test"
+        )
     }
 
     private fun ActivityTagsBinding.setupViews() {
```

### CODE REVIEW

**Comment by wzieba** [comment]
This PR is blocked by 2 things:

- [x] Platform9 request: paaHJt-2zd-p2
- [x] https://github.com/Automattic/simplenote-android/issues/1488

File: Simplenote/src/main/java/com/automattic/simplenote/di/AppModule.kt [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+import dagger.Provides
+import dagger.hilt.InstallIn
+import dagger.hilt.android.qualifiers.ApplicationContext
+import dagger.hilt.components.SingletonComponent
+
+@Module
+@InstallIn(SingletonComponent::class)
+class AppModule {
+    @Provides
+    fun provideSimplenote(@ApplicationContext appContext: Context): Simplenote = appContext as Simplenote
```
Comment (wzieba) [inline Simplenote/src/main/java/com/automattic/simplenote/di/AppModule.kt:15]: I've injected application context as `Simplenote` as it saves us some casting operations. Does it work for you like this or do you prefer previous behaviour?

**Comment by wzieba** [comment]
Hi @danilo04 👋 . This PR (as part of my HACK Week) introduces updated Tracks into the project. Most notably:
- now Simplenote will use Sentry v5.0.1 instead of currently used 1.7.26. You can expect more detailed data in dashboard and more informative crash reports
- Sentry mapping files now works again - it didn't with previous version version of Sentry Gradle Plugin. So you can expect correct stacktraces for minified builds now

I'd be great if you could review and test those changes. I'll be happy to change anything here to align to project style/guidelines.

Thanks!

File: Simplenote/src/main/java/com/automattic/simplenote/di/AppModule.kt (hunk 1 above)
Comment (danilo04) [reply Simplenote/src/main/java/com/automattic/simplenote/di/AppModule.kt:15]: I think this is OK. Since we are going to be refactoring other parts of the app later, we would need to access more and more the `Simplenote` instance. Thus, it will save us lots of cast expressions.

File: Simplenote/src/main/java/com/automattic/simplenote/di/AppModule.kt [hunk 2]
```diff
@@ -0,0 +1,16 @@
...
+import com.automattic.simplenote.Simplenote
+import dagger.Module
+import dagger.Provides
+import dagger.hilt.InstallIn
+import dagger.hilt.android.qualifiers.ApplicationContext
+import dagger.hilt.components.SingletonComponent
+
+@Module
+@InstallIn(SingletonComponent::class)
+class AppModule {
```
Comment (danilo04) [inline Simplenote/src/main/java/com/automattic/simplenote/di/AppModule.kt]: (:pick:) Change the app module to `object` instead of `class`:
```suggestion
object AppModule {
```

**Review by danilo04 — COMMENTED** [review]
Hi @wzieba 👋 .

Thank you for updating `Tracks` and `Sentry` ❤️. These changes were definitely needed. 

I have a small nitpick change (⛏️ ), let me know what do you think?

I have also smoke tested the app and it is working as expected. Regarding the tests recommended:

- Sending events to Sentry
    - After I applied the patch and hit the code where the event was created, the `Sentry` issue was created. ✅ 
    - I injected a bug (NPE) in the app and set `crashLoggingEnabled()` to return `true`. I hit it and crash the app. However, I did not see a Sentry report for that. Am I missing something? ❎ 
- Sending mapping files to Sentry. After running `./gradlew assembleRelease`, I am getting the following error:
```
 Process 'command '/var/folders/61/gv8dx10d20bg3ncbpkf1zz_h0000gn/T/.sentry-cli14922267867924953029.exe''
```

Maybe I am missing something in my environment. Let me know if I have to install something or change a configuration variable in my local setup.

**Comment by wzieba** [comment]
Hi @danilo04 !

Thank you for the review 🙏🏼.

Regarding issue you mentioned:

1. Uploading crash to Sentry will take place on another launch of the app. So if you force-crash with NPE, please open the app once again. Also, Sentry might categorise your crash with "RuntimeException" instead of "NullPointerException". I've tested this and I think it works: please check issue `SIMPLENOTE-ANDROID-3DR` and its message in Sentry dashboard.
2. About sending mapping files to Sentry: I was able to reproduce something similar on my machine with `./gradlew clean assembleRelease --rerun-tasks` - not exact message as yours but R8 was taking too much of Gradle daemon memory. I've increased memory to a higher number in https://github.com/Automattic/simplenote-android/pull/1487/commits/05b1f4f5553ed7ee655e9c884360cfd38b44e37d - it's the same as the one on Woo Android so I hope it's fine.

Could you please confirm if those fixes the issues? Thanks!

**Review by danilo04 — APPROVED** [review]
Hi @wzieba.

I have tested successfully the different scenarios you presented and they work as expected. 
Thank you for the work on this PR. This will improve our visibility on Sentry issues.

**Comment by wzieba** [comment]
Thank you @danilo04 !
