### PR TITLE
Fix ANR related to note count indexing

### LINKED ISSUE #1621: App unresponsive after first launch and moved to background.
> Here is the problem: i can't open settings, because UI stops responding very quickly after application starts (screenshot attached).
 
> I attached logs after cleaning application storage and restart, when application starts without problem, but i think it's useless.

> I suppose after cleaning storage and re-login it works just until next relaunch, when android closes application after it goes to background and than run launch it again when i tap on application icon - that time application becomes unresponsive.

### Expected

App is not unresponsive after subsequent launches. 

### Reproduced

Logs:

```
2023-11-18 11:59:10.887 - LAYOUT: Small, portrait
2023-11-18 11:59:10.903 - NETWORK: WIFI (866,00 Mbps)
2023-11-18 11:59:10.903 - SCREEN: Created (NotesActivity)
2023-11-18 11:59:10.924 - NETWORK: WIFI (866,00 Mbps)
2023-11-18 11:59:10.924 - SCREEN: Created (NoteListFragment)
2023-11-18 11:59:10.937 - ACTION: App opened
2023-11-18 11:59:10.940 - SYNC: Started account bucket (NotesActivity)
2023-11-18 11:59:10.940 - SYNC: Started preference bucket (NotesActivity)
2023-11-18 11:59:10.940 - SYNC: Started note bucket (NotesActivity)
2023-11-18 11:59:10.940 - SYNC: Started tag bucket (NotesActivity)
Access token missing
2023-11-18 11:59:10.944 - SYNC: Stopped account bucket (AuthUtils)
2023-11-18 11:59:10.944 - SYNC: Stopped note bucket (AuthUtils)
2023-11-18 11:59:10.944 - SYNC: Stopped tag bucket (AuthUtils)
2023-11-18 11:59:10.944 - SYNC: Stopped preference bucket (AuthUtils)
2023-11-18 11:59:10.955 - SYNC: Added note bucket listener (NotesActivity)
2023-11-18 11:59:10.955 - SYNC: Added tag bucket listener (NotesActivity)
2023-11-18 11:59:10.960 - SYNC: Added preference bucket listener (NoteListFragment)
2023-11-18 11:59:10.963 - SYNC: Removed preference bucket listener (NoteListFragment)
2023-11-18 11:59:10.963 - SCREEN: Paused (NoteListFragment)
2023-11-18 11:59:10.963 - SYNC: Removed tag bucket listener (NotesActivity)
2023-11-18 11:59:10.963 - SYNC: Removed note bucket listener (NotesActivity)
2023-11-18 11:59:10.963 - SCREEN: Paused (NotesActivity)
2023-11-18 11:59:10.977 - SYNC: Started account bucket (SimplenoteAuthenticationActivity)
2023-11-18 11:59:10.977 - SYNC: Started preference bucket (SimplenoteAuthenticationActivity)
2023-11-18 11:59:10.977 - SYNC: Started note bucket (SimplenoteAuthenticationActivity)
2023-11-18 11:59:10.977 - SYNC: Started tag bucket (SimplenoteAuthenticationActivity)
2023-11-18 11:59:14.514 - SYNC: Started account bucket (SimplenoteCredentialsActivity)
2023-11-18 11:59:14.514 - SYNC: Started preference bucket (SimplenoteCredentialsActivity)
2023-11-18 11:59:14.514 - SYNC: Started note bucket (SimplenoteCredentialsActivity)
2023-11-18 11:59:14.514 - SYNC: Started tag bucket (SimplenoteCredentialsActivity)
2023-11-18 11:59:17.242 - SYNC: Started account bucket (SimplenoteCredentialsActivity)
2023-11-18 11:59:17.242 - SYNC: Started preference bucket (SimplenoteCredentialsActivity)
2023-11-18 11:59:17.243 - SYNC: Started note bucket (SimplenoteCredentialsActivity)
2023-11-18 11:59:17.243 - SYNC: Started tag bucket (SimplenoteCredentialsActivity)
2023-11-18 11:59:19.321 - SYNC: Started account bucket (NotesActivity)
2023-11-18 11:59:19.322 - SYNC: Started preference bucket (NotesActivity)
2023-11-18 11:59:19.322 - SYNC: Started note bucket (NotesActivity)
2023-11-18 11:59:19.322 - SYNC: Started tag bucket (NotesActivity)
2023-11-18 11:59:19.323 - SYNC: Added note bucket listener (NotesActivity)
2023-11-18 11:59:19.323 - SYNC: Added tag bucket listener (NotesActivity)
2023-11-18 11:59:19.338 - SYNC: Added preference bucket listener (NoteListFragment)
2023-11-18 11:59:25.521 - SYNC: Removed preference bucket listener (NoteListFragment)
2023-11-18 11:59:25.521 - SCREEN: Paused (NoteListFragment)
2023-11-18 11:59:25.521 - SYNC: Removed tag bucket listener (NotesActivity)
2023-11-18 11:59:25.521 - SYNC: Removed note bucket listener (NotesActivity)
2023-11-18 11:59:25.521 - SCREEN: Paused (NotesActivity)
2023-11-18 11:59:25.543 - SYNC: Started account bucket (PreferencesActivity)
2023-11-18 11:59:25.544 - SYNC: Started preference bucket (PreferencesActivity)
2023-11-18 11:59:25.544 - SYNC: Started note bucket (PreferencesActivity)
2023-11-18 11:59:25.544 - SYNC: Started tag bucket (PreferencesActivity)
```

Ticket: https://a8c.zendesk.com/agent/tickets/7328023

### PR DESCRIPTION
**Pull request by roundhill**
### Fix #1621

The app has a separate Simperium indexer to keep track of how many notes are in a tag. The query for the indexer was using a `LIKE` comparator which was causing very slow queries when a user has a lot of notes (From my testing, above 400 would cause the ANR)

### Test
1. To reproduce, build the app without this branch and launch the app with around 500 notes in an account. It may need a few tags assigned to some notes as well. Right after launch the app will freeze as the note count indexer goes bananas with long running `LIKE` queries.
2. Apply patch, restart. The app should be responsive-ish straight away!
3. Tap on `edit tags`, the note count displayed there should be accurate.
4. Search for a tag in the search bar, it should show up in the results and work as expected.

### Review
One developer!

### Release
`RELEASE-NOTES.txt` was updated in [fc052ab](https://github.com/Automattic/simplenote-android/pull/1629/commits/fc052ab4e4eee15e83c5ae0780f618b3b3963702) with: 
Fixed the app from becoming unresponsive at launch with a large amount of notes.

### CODE REVIEW

File: Simplenote/src/main/java/com/automattic/simplenote/models/Note.java [hunk 1]
```diff
@@ -99,7 +99,7 @@ public static Query<Note> search(Bucket<Note> noteBucket, String searchString) {
     public static Query<Note> allInTag(Bucket<Note> noteBucket, String tag) {
         return noteBucket.query()
                 .where(DELETED_PROPERTY, ComparisonType.NOT_EQUAL_TO, true)
-                .where(TAGS_PROPERTY, ComparisonType.LIKE, tag);
+                .where(TAGS_PROPERTY, ComparisonType.EQUAL_TO, tag);
```
Comment (dmsnell) [inline Simplenote/src/main/java/com/automattic/simplenote/models/Note.java:102]: how does this work when we have multiple tags on a note?
what is the query doing in SQLite?

Comment (roundhill) [reply Simplenote/src/main/java/com/automattic/simplenote/models/Note.java:102]: The app is creating an index of all of the tags associated with a note:

Screenshot 2024-01-23 at 5 26 50 PM

The query is left joining on that index, something like: 

```
SELECT count(objects.rowid) as `total` FROM `objects` 
LEFT JOIN indexes AS i0 ON objects.bucket = i0.bucket AND objects.key = i0.key AND i0.name="deleted"
LEFT JOIN indexes AS i1 ON objects.bucket = i1.bucket AND objects.key = i1.key AND i1.name="tags"
WHERE objects.bucket = "note" AND (  i0.value IS NULL OR i0.value !=  1) AND (  i1.value IS NOT NULL AND i1.value = "todo") 
```

So I think we're cool to do an equal comparison here! Search still works because it appends a like on a different query.

Comment (dmsnell) [reply Simplenote/src/main/java/com/automattic/simplenote/models/Note.java:102]: oh wow. thanks for clarifying.

I see multiple "opportunities for improvement" here 🙃 

let's try a quick safety-check:
 - search for `buecher` for the tag `bücher`
 - search for `Dog` for the tag `dog`
 - search for `brau` for `bräu`

I'm not familiar with the querying (you might be) and so thought we should verify that there's no language-sensitive behavior incorporated into `LIKE`

otherwise, totally :shipit:

**Review by dmsnell — COMMENTED** [review]
found another case in https://github.com/Automattic/simplenote-android/blob/3b303f070b4124627f14c8018407b207b2e56f8d/Simplenote/src/main/java/com/automattic/simplenote/models/Tag.java#L132-L134

also we added some code to normalize tag values because of language and Unicode differences. this may be of use to you here, even if not directly for the code.

https://github.com/Automattic/simplenote-android/blame/3b303f070b4124627f14c8018407b207b2e56f8d/Simplenote/src/main/java/com/automattic/simplenote/utils/TagUtils.java#L117-L134

File: Simplenote/src/main/java/com/automattic/simplenote/models/Note.java (hunk 1 above)
Comment (roundhill) [reply Simplenote/src/main/java/com/automattic/simplenote/models/Note.java:102]: Search is using a different query for tag suggestions with a `LIKE`, and those searches don't bring up matches :|(except for the `Dog` one as it doesn't seem to be case sensitive)

We'll have to poke at that to see if we can fix it or if it's a limitation of SQLite 3

**Review by danilo04 — APPROVED** [review]
Hi @roundhill the fix works for preventing the ANR. However, some now the tag count and the tag selection (when the user taps on a tag in the navigation drawer) are case sensitive. Before it was case insensitive. I think we have to find a way to index the hash tag (`TagUtils.hashTag(name)`) instead of the tags' name. 

I am approving the PR but it would be nice to add a better fix in the future. Also, I would like to trace back why Simperium is executing the query in the main thread. It seems weird.
